# Generated by Django 4.2 on 2023-04-26 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date(2023, 4, 26), verbose_name="Date"
                    ),
                ),
                ("theme", models.CharField(max_length=200, verbose_name="Theme")),
                (
                    "homework",
                    models.CharField(max_length=1000, verbose_name="Homework"),
                ),
                ("mark", models.IntegerField(default=None, verbose_name="Mark")),
            ],
        ),
    ]
