# Generated by Django 4.2 on 2023-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=25, verbose_name="Word")),
                (
                    "translation",
                    models.CharField(max_length=100, verbose_name="Translation"),
                ),
            ],
        ),
    ]
